---

is_debug: true
listen:
  type: sock #или tcp
#  bind_ip: 0.0.0.0
#  port: 10000
mongodb:
  host: localhost
  port: 27017
  database: user-service
  auth_db:
  username:
  password:
  collection: users