---

is_debug: true
listen:
  type: tcp #или tcp
  bind_ip: 0.0.0.0
  port: 10000
mongodb:
  host: 192.168.99.100 #localhost
  port: 27017
  database: user-service
  auth_db:
  username:
  password:
  collection: users